// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udituntwllttyejobufm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkaXR1bnR3bGx0dHllam9idWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDcyOTUsImV4cCI6MjA2ODAyMzI5NX0.AlMbHfIZWDH2_wQoqx9-mu5FjV2AggNlh5ldj_HxN6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'ship-with-tosin-auth',
    flowType: 'pkce'
  }
});